blank_issues_enabled: false
contact_links:
  - name: Report a security issue
    url: https://volitexai.tech
    about: Please report security vulnerabilities to the security team.
  - name: Product Documentation
    url: https://volitexai.tech
    about: If you have questions or need to understand the product better, check our documentation.
